
meta_product_name: "Gift Me"
meta_title: "Gift Me - Your own discount wallet!"
meta_description: "Browse the web for discounts. Organize them and never miss an opportunity again!"
meta_image: "og_image.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"    # required for Twitter Cards
